//turn
export const SET_TURN = "SET_TURN";

//battle status
export const BATTLE_END = "BATTLE_END";
export const BATTLE_START = "BATTLE_START";
export const SET_WINNER = "SET_WINNER";
export const SHOW_INFO = "SHOW_INFO";
export const HIDE_INFO = "HIDE_INFO";
export const SET_BATTLE_INFO_DATA = "SET_BATTLE_INFO_DATA";
export const SET_UI_ENABLED = "SET_UI_ENABLED";
export const ADD_LOG = "ADD_LOG";

//player
export const PLAYER_RESET_STATS = "PLAYER_RESET_STATS";
export const PLAYER_HP_SUBSTRACT = "PLAYER_HP_SUBSTRACT";
export const PLAYER_HP_ADD = "PLAYER_HP_ADD";
export const PLAYER_AP_SUBSTRACT = "PLAYER_AP_SUBSTRACT";
export const PLAYER_AP_RESET = "PLAYER_AP_RESET";
export const PLAYER_EFFECT_ADD = "PLAYER_EFFECT_ADD";
export const PLAYER_EFFECT_SUBSTRACT = "PLAYER_EFFECT_SUBSTRACT";
export const PLAYER_EFFECT_TURN_SUBSTRACT = "PLAYER_EFFECT_TURN_SUBSTRACT";
export const PLAYER_ATTACK_USES_PER_BATTLE_SUBSTRACT = "PLAYER_ATTACK_USES_PER_BATTLE_SUBSTRACT";
export const PLAYER_UTILITY_USES_PER_BATTLE_SUBSTRACT = "PLAYER_UTILITY_USES_PER_BATTLE_SUBSTRACT";
export const PLAYER_UTILITY_EFFECT_ADD = "PLAYER_UTILITY_EFFECT_ADD";
export const PLAYER_UTILITY_EFFECT_SUBSTRACT = "PLAYER_UTILITY_EFFECT_SUBSTRACT";
export const PLAYER_UTILITY_EFFECT_TURN_SUBSTRACT = "PLAYER_UTILITY_EFFECT_TURN_SUBSTRACT";
export const PLAYER_CHANGE_STATS = "PLAYER_CHANGE_STATS";

//enemy
export const ENEMY_RESET_STATS = "ENEMY_RESET_STATS";
export const ENEMY_HP_SUBSTRACT = "ENEMY_HP_SUBSTRACT";
export const ENEMY_HP_ADD = "ENEMY_HP_ADD";
export const ENEMY_AP_SUBSTRACT = "ENEMY_AP_SUBSTRACT";
export const ENEMY_AP_RESET = "ENEMY_AP_RESET";
export const ENEMY_EFFECT_ADD = "ENEMY_EFFECT_ADD";
export const ENEMY_EFFECT_TURN_SUBSTRACT = "ENEMY_EFFECT_TURN_SUBSTRACT";
export const ENEMY_EFFECT_SUBSTRACT = "ENEMY_EFFECT_SUBSTRACT";
export const ENEMY_ATTACK_USES_PER_BATTLE_SUBSTRACT = "ENEMY_ATTACK_USES_PER_BATTLE_SUBSTRACT";

